### ISSUE TITLE
frontend api

### ISSUE THREAD

**Issue by ausir0726** [finpo/qtace#1]
- [x] 首頁輪撥圖
- [x] 取得分類資訊
- [x] 取得文章資訊
- [x] 取得產品資訊
- [x] 取得靜態文案
- [x] 會員資訊
  - [x] 會員註冊
  - [x] 會員登入
  - [x] 會員資料修改
  - [x] 訂單查詢
  - [x] 忘記密碼
- [x] 訂購 - 取得訂購清單金額（檢查庫存）
- [x] 訂購 - 輸入訂單資訊成立訂單（付款方式仍要傳送）
- [x] 寄送聯絡我們信件
- [x] 取得系統變數

* 信用卡串接取消 （ 2015-01-20 ）
* 產品的分類使用 [id],[id],[id] 分隔 , 查詢分類使用 like

**Comment by ausir0726** [comment]
1/26  首頁輪撥圖 , 取得分類資訊(menu) , 取得文章資訊 , 取得產品資訊 , 取得靜態文案 , 會員資訊 , 取得系統變數

**Comment by joanne3634** [comment]
前台api文件位置：http://docs.qtacefrontend.apiary.io/

**Comment by ausir0726** [comment]
@joanne3634 
聯絡我們寄送 功能正常 ，但 回應有 dump 忘記關掉了 
<pre>array(4) {
  [&quot;name&quot;] =&gt; string(9) &quot;羅常瑋&quot;
  [&quot;phone&quot;] =&gt; string(10) &quot;0920917941&quot;
  [&quot;mail&quot;] =&gt; string(18) &quot;ausir@finpo.com.tw&quot;
  [&quot;content&quot;] =&gt; string(81) &quot;我想要買背包，但是一直找不到適合的，可以幫我訂做一款嘛&quot;
}
</pre>{"success":true}

**Comment by ausir0726** [comment]
@joanne3634 
item 缺了 list 功能

**Comment by ausir0726** [comment]
all test OK , good job !
