### ISSUE TITLE
0327 bug fix

### ISSUE THREAD

**Issue by ausir0726** [finpo/qtace#10]
- [x] CKEDITOR 請開啟排版「置中」的按鈕
- [x] CKEDITOR 圖片上傳故障
- [x] CKEDITOR 圖片上傳裡面的 CKFINDER 無法打開
- [x] 修改商品/文章/訂單 等 popup window 在小視窗會無法按到存檔等下面的按鈕

功能調整
- [x] 更改產品分類由產品更改分類（使用樹狀圖勾選）

**Comment by joanne3634** [comment]
更改成產品那邊有分類管理使用勾選 選單管理中的商品管理移除
Administrator / config / module.config.php 
Administrator / src / Administrator / Controller / ItemCategorySelectItemTreeController.php 
Administrator / src / Administrator / Model / ItemCategorySelectItemTree.php 
js / app / view / itemcategorywindow
js / app/ store / categoryselectarraystore 
js / app / view / categorysubpanel
js / app / view / itemGridPanel
Qtace issue都修完了!

**Comment by ausir0726** [comment]
checked
