### ISSUE TITLE
0424 後台修正項目

### ISSUE THREAD

**Issue by ausir0726** [finpo/qtace#12]
請參閱文件 QTACE官網前台-三校.docx 
檔案放在 chatwork qtace 群組

- [ ] 訂單管理 增加欄位 「備註」「物流編號」 （後台2）
- [ ] 訂單列表 增加顯示欄位 「訂購人」「收件人」「備註」（後台2a）
- [ ] 訂單列表 多選後可發出貨通知信件（內含物流編號）（後台2b）

**Comment by joanne3634** [comment]
改完了~~ 
除了上面三個issue以外
我還有改文件裡面的後台1  ( 產品編輯視窗改為直列並調整高度 )

有改到的地方
__Database__ 
order_main 
__Backend UI__ 
ItemWindow.js
OrderWindow.js 
OrderModel.js 
OrderModel.js 
OrderGridPanel.js 
Order.php

**Comment by joanne3634** [comment]
這邊改完的有看到嗎 @@?

**Comment by ausir0726** [comment]
有看到喔！但是因為 cera 那邊還在調整 ，還沒交付客戶
