### ISSUE TITLE
缺少訂單列印

### ISSUE THREAD

**Issue by ausir0726** [finpo/qtace#9]
- [x] 訂單列印

少了訂單列印的功能喔

**Comment by ausir0726** [comment]
謝謝

**Comment by joanne3634** [comment]
是做在後台訂單管理裏面嗎
單筆訂單列印？
直接印還是需要格式的吐資料？

從我的 iPhone 傳送

羅 常瑋 <notifications@github.com<mailto:notifications@github.com>> 於 2015年3月26日 上午10:10 寫道：


  *    訂單列印

少了訂單列印的功能喔

**Comment by ausir0726** [comment]
訂單管理，單筆訂單明細的列印，吐資料，要另外排版

**Comment by joanne3634** [comment]
Ok 我等等下課改

從我的 iPhone 傳送

羅 常瑋 <notifications@github.com<mailto:notifications@github.com>> 於 2015年3月26日 下午12:40 寫道：


訂單管理，單筆訂單明細的列印，吐資料，要另外排版

**Comment by joanne3634** [comment]
A. 已修正 
1. 訂單列印
OrderGridPanel.js  < fn:onPrintClick > 
Order.php  
![image](https://cloud.githubusercontent.com/assets/7580346/6912136/0f791362-d79e-11e4-97e0-a51b5c70e028.png)

2. CKEDITOR 請開啟排版「置中」的按鈕
下載justify < http://ckeditor.com/addon/justify > 放在 js / administrator / Qtace / ckeditor / plugins 
 js / administrator / Qtace / ckeditor / config.js  < extraPlugins > 
3. 上傳相關故障
 js / administrator / Qtace / ckeditor / config.js  < file 路徑們有錯 > 
4. 修改商品/文章/訂單 等 popup window 在小視窗會無法按到存檔等下面的按鈕
OrderWindow.js ArticleWindow.js ItemWindow.js MyViewPort.js 
B. 還未修正 
1. 樹狀圖勾選

**Comment by ausir0726** [comment]
checked
